import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage();
page.on('pageerror', (e) => console.log('PAGEERROR:', e.message));
page.on('console', (msg) => console.log('CONSOLE:', msg.type(), msg.text()));
await page.goto('http://localhost:8000/Fronend/pages/review.html', { waitUntil: 'networkidle' });
await page.waitForTimeout(800);
await page.click('#composer .lock-overlay [data-auth-open="login"]');
await page.waitForTimeout(400);
await page.click('[data-auth-tab="register"]');
await page.waitForTimeout(300);
const email = `ui-regdebug-${Date.now()}@example.com`;
await page.fill('#register-name', 'ทดสอบUI');
await page.fill('#register-email', email);
await page.fill('#register-password', 'TestUi123!');
await page.fill('#register-birthdate', '2000-01-01');
await page.check('#register-terms');
await page.click('#auth-panel-register button[type="submit"]');
await page.waitForTimeout(3500);
console.log('final session:', await page.evaluate(() => window.MNX_AUTH?.getSession()?.email));
console.log('cleanup email:', email);
await browser.close();
