import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage();
page.on('pageerror', (e) => console.log('PAGEERROR:', e.message));
await page.goto('http://localhost:8000/Fronend/pages/attractions.html', { waitUntil: 'networkidle' });
await page.waitForTimeout(800);
await page.evaluate(() => document.querySelectorAll('[data-auth-open="register"]')[0].click());
await page.waitForTimeout(500);
const email = `ui-attr-regdebug-${Date.now()}@example.com`;
await page.fill('#register-name', 'ทดสอบAttr');
await page.fill('#register-email', email);
await page.fill('#register-password', 'TestAttr123!');
await page.fill('#register-birthdate', '2000-01-01');
await page.check('#register-terms');
await page.click('#auth-panel-register button[type="submit"]');
await page.waitForTimeout(3500);
console.log('final session:', await page.evaluate(() => window.MNX_AUTH?.getSession()?.email));
console.log('cleanup email:', email);
await browser.close();
